# Generated by Django 2.2.4 on 2019-08-12 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_id', models.CharField(max_length=6)),
                ('nr_of_stations', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('interval_below', models.FloatField()),
                ('interval_above', models.FloatField()),
            ],
        ),
    ]
